#!/usr/bin/env python3
import serial
def main():
    print("hello world")
    file = open("index.html","w")

    file.write("""
<!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <title></title>
        </head>
        <body>""" + get_temp() + """

        </body>
        </html>""")

def get_temp():
    arduino = serial.Serial('COM5', 9600, timeout=.1)
    return arduino.readline()[:-2]
if __name__ == "__main__":
    main()
